name: "Anchore Notify"
description: "Create Github job summaries and slack messages for Anchore scan results"
author: "Rob Sitro"
inputs:
  sarif_data:
    description: "Anchore SARIF data"
    required: True
  severity_cutoff_num:
    description: "Anchore severity number threshold that will generate notifications"
    required: False
    default: 8
  slack_token:
    description: "Your Slack bot token"
    required: True
  slack_channel:
    description: "The Slack channel ID you want to send messages to"
    required: True
  report_name:
    description: "A name for your report that will be included in the notifications"
    required: True
runs:
  using: "docker"
  image: "Dockerfile"
